#!/bin/bash

# 	Local	Dest
MAP="	html	/var/www/
	bin	/usr/
	etc	/"

SKIP='/.gitignore
/Makefile
/i_watcher.c'

. which_files


verbose=''
diff_args=''
while (( $# >= 1 ))
do
  if [[ 'x-r' == "x$1" ]]
  then
    reverse_diff=y
    shift
    continue
  elif [[ "x$1" != "x${1#-}" ]]
  then
    diff_args="$diff_args $1"
    shift
    continue
  elif [[ "x-v" != "x$1" ]]
  then
    verbose=y
    diff_args="$diff_args "
    shift
    continue
  else
    break
  fi
done

tot=0
mat=0

echo "$MAP" |
 while read localdir destdir
 do
    exec {file_list}< <(find "$localdir" -type f -print | fgrep -v "$SKIP")
     while read f <&${file_list}
     do
       if diff -q "$f" "$destdir/$f" >/dev/null
       then
         let mat++
       else
         echo -ne "\r                \r" >&2
         echo -e "$f"
         #ls -l "$f" "$destdir/$f"
         if [[ -n "$diff_args" && -f "$destdir/$f" && -f "$f" ]]
         then
	   echo
           if [[ y = "$reverse_diff" ]]
           then
             diff $diff_args "$f" "$destdir/$f"
           else
             diff $diff_args "$destdir/$f" "$f"
           fi
	   echo
         fi
       fi
       let tot++
       printf "\r%4d/%d    " $mat $tot >&2
     done
 done
echo >&2
