#!/bin/bash


cat <<EOF
HTTP/1.1 301 Moved Permanently
Content-Type: text/html; charset=UTF-8
Location: http://192.168.5.1/HSV_Timing/Results/results_ft.html
Server: Dodgy-Dave-Redirector/10.0
Date: $(TZ=0 date "+%a, %d %b %Y %T GMT")
expires: $(TZ=0 date "+%a, %d %b %Y %T GMT")
pragma: no-cache
Connection: close
Content-Length: 175

<head><title>HSVFest Timing Redirect</title></head>
<body><h1>HSVFest Timing Redirect</h1>HSVFest Timing Redirect may be found <a HREF="http://192.168.5.1/HSV_Timing/Results/results_ft.html">here</a></body>
EOF

received=''
while read -t 0 krud
do
  received="${received}${krud}"
  read -t 1 krud2
  received="${received}${krud2}"
  [[ "$krud$krud2" == '' ]] && break
done

logger -t web_redir -id "${received}"
date="$(date -Iseconds)"
echo "${date}: ${received}" | sed 's/\r/#015/g' >> /var/www/log/web_redir.log

exec >&-
exec 2>&-
exec <&-
