#!/bin/bash

# lrwxrwxrwx 1 root root   35 May 14  2022 10-accesslog.conf -> ../conf-available/10-accesslog.conf
# lrwxrwxrwx 1 root root   37 May 14  2022 10-dir-listing.conf -> ../conf-available/10-dir-listing.conf
# lrwxrwxrwx 1 root root   37 May 14  2022 15-fastcgi-php.conf -> ../conf-available/15-fastcgi-php.conf
# lrwxrwxrwx 1 root root   33 May 14  2022 10-fastcgi.conf -> ../conf-available/10-fastcgi.conf

echo "TrackTiming post install  $0 $*"

if [ "$1" = "configure" ]; then
    echo "####  Adding some links to enable features in lighttps"
    ln -s ../conf-available/10-accesslog.conf ../conf-available/10-dir-listing.conf ../conf-available/10-fastcgi.conf ../conf-available/15-fastcgi-php.conf /etc/lighttpd/conf-enabled ||
     true
fi



